name: wordpress_client
description: A Dart wrapper for Wordpress REST API.
version: 0.0.1
# homepage: https://www.example.com
author: Kevin Birch <kevin@kevinbirch.com>

environment:
  sdk: '>=2.0.0-dev.52.0 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.30
