name: wordpress_client
description: A Dart wrapper for Wordpress REST API.
version: 0.0.1
# homepage: https://www.example.com
author: Kevin Birch <kevin@kevinbirch.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.11.3

dev_dependencies:
  test: ^1.0.0
